import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ops Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Ops Manager
        </h1>

        <div className={styles.grid}>
          <a href="builds" className={styles.card}>
            <h2>Builds &rarr;</h2>
          </a>

          <a href="events" className={styles.card}>
            <h2>Github events &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
