import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Ops Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-center">
        Ops Manager
      </h1>
      <div className="row">
        <div className="col-7">
          <div className="container">
            <div class="row">
              <div className="col-12">
                <form className="card ">
                  <div className="card-header">
                    <h5>Install Github app</h5>
                  </div>
                  <div className="card-body">
                    <div className="row">
                      <label for="githubUserOrOrg" className="col-form-label-sm col-sm-3 ">Github account type:</label>

                      <div className="form-check form-check-inline col-sm-1 pt-2">
                        <input className="form-check-input" type="radio" name="githubUserOrOrg" id="radioUser" />
                        <label className="form-check-label" for="radioUser">
                          User
                        </label>
                      </div>
                      <div className="form-check form-check-inline col pt-2">
                        <input className="form-check-input" type="radio" name="githubUserOrOrg" id="radioOrg" />
                        <label className="form-check-label" for="radioOrg">
                          Org
                        </label>
                      </div>
                    </div>

                    <div className="row">
                      <label for="githubName" className="col-form-label-sm col-sm-3">Github name:</label>
                      <div className="col pt-2">
                        <input type="text" className="form-control" id="githubName" />
                      </div>
                    </div>
                    <div className="row">
                      <div className="col-sm-3">
                        <label className="visually-hidden">Save button</label>
                      </div>
                      <div className="col pt-2">
                        <button type="button" className="btn btn-primary">Install</button>
                      </div>
                    </div>
                  </div>

                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer className="row">
      </footer>
    </div>
  )
}
